##
# Upptime Config - status.onetimesecret.com (2024-05-24)
#
# See:
#   - https://upptime.js.org/docs/configuration
#
owner: onetimesecret
repo: status

sites:
  - name: Homepage
    url: https://onetimesecret.com/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
    headers:
      - "OTS-VIA: upptime"
  - name: Homepage (staging)
    url: $STAGING_HOST
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
    headers:
      - "OTS-VIA: upptime"
  - name: App Support
    url: https://app.onetimesecret.com/
  - name: API (v1)
    url: https://onetimesecret.com/api/v1/status
    __dangerous__body_down_if_text_missing: '"status":"nominal"'

# Delay (in milliseconds) that will occur between checking each
# configured endpoint. Default: 0.
delay: 2000

# Status issues open for less than 15 minutes are deleted instead.
skipDeleteIssues: true

# Default github username to assign issue tickets
assignees:
  - delano

status-website:
  cname: status.onetimesecret.com
  logoUrl: https://onetimesecret.com/img/logo-96.png
  name: Status - Onetime Secret
  introTitle: Real-time status and uptime monitoring for Onetime Secret.
  introMessage: This is a our status page which uses **real-time** data from our [GitHub repository](https://github.com/onetimesecret/status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://upptime.js.org)
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Return to home
      href: https://onetimesecret.com/

# Disable auto-updates for repo description, topics, and homepage
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
